import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const Cores = {
  bgRoot: '#06110D',
  bgDeep: '#071018',
  surfaceGlass: 'rgba(8, 28, 25, 0.82)',
  surfaceGlassSoft: 'rgba(13, 35, 38, 0.64)',
  surfaceGlassCard: 'rgba(10, 30, 24, 0.88)',
  portalGreen: '#7FFF00',
  portalGreen2: '#55FF55',
  acidLime: '#B6FF37',
  cyan: '#35E7F2',
  dimensionPurple: '#8B5CF6',
  indigo: '#6366F1',
  accentYellow: '#FBBF24',
  textPrimary: '#F8FAFC',
  textSecondary: '#CBD5E1',
  textMuted: '#94A3B8',
  textDark: '#07110D',
  borderGreen: 'rgba(127, 255, 0, 0.30)',
  borderCyan: 'rgba(53, 231, 242, 0.25)',
  borderPurple: 'rgba(139, 92, 246, 0.28)',
  borderYellow: 'rgba(251, 191, 36, 0.30)',
  borderGlass: 'rgba(255, 255, 255, 0.08)',
  glowGreen: 'rgba(85, 255, 85, 0.18)',
  glowPurple: 'rgba(139, 92, 246, 0.14)',
  overlayDark: 'rgba(6, 17, 13, 0.72)',
};

export const Tokens = {
  spacing: {
    xs: 4,
    sm: 8,
    md: 14,
    lg: 20,
    xl: 28,
  },
  radius: {
    sm: 8,
    md: 14,
    lg: 18,
    xl: 24,
    full: 9999,
  },
  maxWidth: 480,
  minTouchArea: 48,
};

export const EstilosGlobais = StyleSheet.create({
  containerSeguro: {
    flex: 1,
    backgroundColor: Cores.bgRoot,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
    alignItems: 'center',
  },
  contentWrapper: {
    width: '100%',
    maxWidth: Tokens.maxWidth,
  },
  headerBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  overlineBadge: {
    backgroundColor: Cores.surfaceGlassSoft,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: Tokens.radius.full,
    borderWidth: 1,
    borderColor: Cores.borderGreen,
  },
  overlineText: {
    fontSize: 11,
    fontWeight: '800',
    color: Cores.portalGreen,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  tituloTela: {
    fontSize: 28,
    fontWeight: '900',
    color: Cores.textPrimary,
    letterSpacing: 1,
    lineHeight: 34,
    marginBottom: 4,
  },
  subtituloTela: {
    fontSize: 14,
    fontWeight: '500',
    color: Cores.textSecondary,
    lineHeight: 20,
    marginBottom: 16,
  },
  tagGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginVertical: 12,
  },
  tagChip: {
    backgroundColor: Cores.surfaceGlassSoft,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Cores.borderGreen,
  },
  tagChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: Cores.portalGreen,
    letterSpacing: 1,
  },
  cardPadrao: {
    backgroundColor: Cores.surfaceGlassCard,
    borderRadius: Tokens.radius.lg,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Cores.borderGreen,
    shadowColor: Cores.portalGreen,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  cardTituloRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    gap: 8,
  },
  cardPill: {
    width: 6,
    height: 14,
    borderRadius: 3,
    backgroundColor: Cores.portalGreen,
  },
  cardTitulo: {
    fontSize: 14,
    fontWeight: '800',
    color: Cores.textPrimary,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  cardTexto: {
    fontSize: 13,
    color: Cores.textSecondary,
    lineHeight: 19,
  },
  botaoPrimario: {
    backgroundColor: Cores.portalGreen,
    minHeight: 52,
    borderRadius: Tokens.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    shadowColor: Cores.portalGreen,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 5,
  },
  textoBotaoPrimario: {
    color: Cores.textDark,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
});

export const EstilosPortal = StyleSheet.create({
  containerPortal: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 14,
    position: 'relative',
  },
  glowExterno: {
    position: 'absolute',
    borderRadius: Tokens.radius.full,
    backgroundColor: Cores.glowGreen,
  },
  ringExterno: {
    position: 'absolute',
    borderRadius: Tokens.radius.full,
    borderWidth: 2,
    borderColor: Cores.borderGreen,
    borderStyle: 'dashed',
  },
  ringInterno: {
    position: 'absolute',
    borderRadius: Tokens.radius.full,
    borderWidth: 1.5,
    borderColor: Cores.borderCyan,
    borderStyle: 'dotted',
  },
  imagemPortal: {
    resizeMode: 'contain',
  },
  particula: {
    position: 'absolute',
    borderRadius: Tokens.radius.full,
    backgroundColor: Cores.portalGreen2,
  },
});

export const EstilosTela1 = StyleSheet.create({
  heroArea: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    marginVertical: 12,
  },
  portalFundo: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  imagemHero: {
    width: Math.min(width * 0.85, 360),
    height: Math.min(width * 0.85, 360),
    resizeMode: 'contain',
    zIndex: 2,
  },
  blocoIntro: {
    backgroundColor: Cores.surfaceGlass,
    borderRadius: Tokens.radius.lg,
    padding: 18,
    borderWidth: 1,
    borderColor: Cores.borderGreen,
    marginTop: 8,
    marginBottom: 10,
  },
  badgeDestak: {
    fontSize: 12,
    fontWeight: '800',
    color: Cores.portalGreen,
    letterSpacing: 2,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  descricaoIntro: {
    fontSize: 14,
    color: Cores.textSecondary,
    lineHeight: 21,
  },
});

export const EstilosTela2 = StyleSheet.create({
  heroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Cores.surfaceGlassSoft,
    borderRadius: Tokens.radius.xl,
    padding: 16,
    borderWidth: 1,
    borderColor: Cores.borderCyan,
    marginVertical: 14,
    overflow: 'hidden',
  },
  rickImagem: {
    width: 150,
    height: 190,
    resizeMode: 'contain',
  },
  rickHeaderInfo: {
    flex: 1,
    paddingLeft: 12,
  },
  cardCientifico: {
    backgroundColor: Cores.surfaceGlassCard,
    borderRadius: Tokens.radius.lg,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Cores.borderCyan,
  },
  pillCyan: {
    width: 6,
    height: 14,
    borderRadius: 3,
    backgroundColor: Cores.cyan,
  },
  tituloCyan: {
    fontSize: 14,
    fontWeight: '800',
    color: Cores.cyan,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Cores.portalGreen,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '700',
    color: Cores.portalGreen,
  },
});

export const EstilosTela3 = StyleSheet.create({
  heroAssimetrico: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Cores.surfaceGlassSoft,
    borderRadius: Tokens.radius.xl,
    padding: 16,
    borderWidth: 1,
    borderColor: Cores.borderYellow,
    marginVertical: 14,
    overflow: 'hidden',
  },
  mortyInfoBox: {
    flex: 1,
    paddingRight: 12,
  },
  mortyImagem: {
    width: 140,
    height: 190,
    resizeMode: 'contain',
  },
  cardMorty: {
    backgroundColor: Cores.surfaceGlassCard,
    borderRadius: Tokens.radius.lg,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Cores.borderYellow,
  },
  pillYellow: {
    width: 6,
    height: 14,
    borderRadius: 3,
    backgroundColor: Cores.accentYellow,
  },
  tituloYellow: {
    fontSize: 14,
    fontWeight: '800',
    color: Cores.accentYellow,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  quoteBox: {
    backgroundColor: 'rgba(251, 191, 36, 0.08)',
    borderRadius: Tokens.radius.md,
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: Cores.accentYellow,
    marginVertical: 10,
  },
  quoteText: {
    fontSize: 13,
    fontStyle: 'italic',
    color: Cores.textSecondary,
    lineHeight: 19,
  },
});

export const EstilosTela4 = StyleSheet.create({
  cidadelaCard: {
    width: '100%',
    height: 220,
    borderRadius: Tokens.radius.xl,
    overflow: 'hidden',
    position: 'relative',
    marginVertical: 14,
    borderWidth: 1,
    borderColor: Cores.borderPurple,
  },
  cidadelaImagem: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  cidadelaOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Cores.overlayDark,
    padding: 16,
    justifyContent: 'flex-end',
  },
  cidadelaBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(139, 92, 246, 0.35)',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Cores.borderPurple,
    marginBottom: 6,
  },
  cidadelaBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: Cores.dimensionPurple,
    letterSpacing: 1.5,
  },
  cidadelaTitulo: {
    fontSize: 20,
    fontWeight: '900',
    color: Cores.textPrimary,
    letterSpacing: 0.5,
  },
  cardDimensional: {
    backgroundColor: Cores.surfaceGlassCard,
    borderRadius: Tokens.radius.lg,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Cores.borderPurple,
  },
  pillPurple: {
    width: 6,
    height: 14,
    borderRadius: 3,
    backgroundColor: Cores.dimensionPurple,
  },
  tituloPurple: {
    fontSize: 14,
    fontWeight: '800',
    color: Cores.dimensionPurple,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  portalMenorContainer: {
    alignItems: 'center',
    marginVertical: 14,
    padding: 14,
    backgroundColor: Cores.surfaceGlassSoft,
    borderRadius: Tokens.radius.lg,
    borderWidth: 1,
    borderColor: Cores.borderGreen,
  },
  fimViagemTexto: {
    fontSize: 13,
    fontWeight: '700',
    color: Cores.textMuted,
    letterSpacing: 1.5,
    marginTop: 8,
    textTransform: 'uppercase',
  },
});
